version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    build:
      context: ./docker/db/
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "8047:5432"

volumes:
    db_data:
